#!/usr/bin/env python3
"""
NNUE Training Script for Blunder Chess Engine

Reads training data generated by the engine's self-play mode and trains
a neural network to predict search evaluations.

Architecture: HalfKP (768 → 256 → 32 → 32 → 1)
- Input: 768 features (6 piece types × 2 colors × 64 squares)
- Hidden layers: 256 → 32 → 32
- Output: 1 (evaluation score)

Usage:
    python scripts/train_nnue.py --input training_data.bin --output weights.bin
"""

import argparse
import struct
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from pathlib import Path
from typing import Tuple


class NNUEDataset(Dataset):
    """Dataset for NNUE training data."""
    
    def __init__(self, data_path: str):
        """Load training data from binary file.
        
        Format: [768 floats: features][1 float: search score][1 float: game result]
        Each entry is 3080 bytes (768×4 + 4 + 4)
        """
        self.entry_size = 768 * 4 + 4 + 4  # 3080 bytes
        
        with open(data_path, 'rb') as f:
            data = f.read()
        
        num_entries = len(data) // self.entry_size
        print(f"Loading {num_entries} training positions from {data_path}")
        
        self.features = []
        self.targets = []
        
        for i in range(num_entries):
            offset = i * self.entry_size
            entry = data[offset:offset + self.entry_size]
            
            # Parse entry
            features = struct.unpack('768f', entry[:768*4])
            search_score = struct.unpack('f', entry[768*4:768*4+4])[0]
            game_result = struct.unpack('f', entry[768*4+4:768*4+8])[0]
            
            self.features.append(features)
            # Use search score as target (could also blend with game result)
            self.targets.append(search_score)
        
        self.features = torch.tensor(self.features, dtype=torch.float32)
        self.targets = torch.tensor(self.targets, dtype=torch.float32).unsqueeze(1)
        
        print(f"Features shape: {self.features.shape}")
        print(f"Targets shape: {self.targets.shape}")
        print(f"Target range: [{self.targets.min():.2f}, {self.targets.max():.2f}]")
    
    def __len__(self):
        return len(self.features)
    
    def __getitem__(self, idx):
        return self.features[idx], self.targets[idx]


class NNUENetwork(nn.Module):
    """NNUE Neural Network: HalfKP (768 → 256 → 32 → 32 → 1)"""
    
    def __init__(self):
        super(NNUENetwork, self).__init__()
        
        # Feature transformer: 768 → 256
        self.fc1 = nn.Linear(768, 256)
        
        # Hidden layers: 256 → 32 → 32
        self.fc2 = nn.Linear(256, 32)
        self.fc3 = nn.Linear(32, 32)
        
        # Output layer: 32 → 1
        self.fc4 = nn.Linear(32, 1)
        
        # Activation
        self.relu = nn.ReLU()
    
    def forward(self, x):
        # Feature transformer
        x = self.relu(self.fc1(x))
        
        # Hidden layers
        x = self.relu(self.fc2(x))
        x = self.relu(self.fc3(x))
        
        # Output (no activation - raw score)
        x = self.fc4(x)
        
        return x


def export_weights(model: NNUENetwork, output_path: str):
    """Export trained weights to binary format for C++ engine.
    
    Format:
    - All weights and biases in layer order
    - Each value is a 32-bit float (little-endian)
    """
    print(f"\nExporting weights to {output_path}")
    
    with open(output_path, 'wb') as f:
        # Export each layer's weights and biases
        for name, param in model.named_parameters():
            weights = param.detach().cpu().numpy().flatten()
            print(f"  {name}: {len(weights)} values")
            
            # Write as 32-bit floats
            for w in weights:
                f.write(struct.pack('f', w))
    
    print(f"Exported {sum(p.numel() for p in model.parameters())} total parameters")


def train_nnue(
    data_path: str,
    output_path: str,
    epochs: int = 10,
    batch_size: int = 256,
    learning_rate: float = 0.001,
    device: str = 'cuda' if torch.cuda.is_available() else 'cpu'
):
    """Train NNUE network on self-play data."""
    
    print(f"Using device: {device}")
    
    # Load dataset
    dataset = NNUEDataset(data_path)
    
    # Split into train/validation (90/10)
    train_size = int(0.9 * len(dataset))
    val_size = len(dataset) - train_size
    train_dataset, val_dataset = torch.utils.data.random_split(
        dataset, [train_size, val_size]
    )
    
    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
    val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False)
    
    print(f"Train set: {train_size} positions")
    print(f"Validation set: {val_size} positions")
    
    # Create model
    model = NNUENetwork().to(device)
    print(f"\nModel architecture:")
    print(model)
    print(f"Total parameters: {sum(p.numel() for p in model.parameters())}")
    
    # Loss and optimizer
    criterion = nn.MSELoss()
    optimizer = optim.Adam(model.parameters(), lr=learning_rate)
    
    # Training loop
    print(f"\nTraining for {epochs} epochs...")
    best_val_loss = float('inf')
    
    for epoch in range(epochs):
        # Training
        model.train()
        train_loss = 0.0
        
        for features, targets in train_loader:
            features, targets = features.to(device), targets.to(device)
            
            optimizer.zero_grad()
            outputs = model(features)
            loss = criterion(outputs, targets)
            loss.backward()
            optimizer.step()
            
            train_loss += loss.item()
        
        train_loss /= len(train_loader)
        
        # Validation
        model.eval()
        val_loss = 0.0
        
        with torch.no_grad():
            for features, targets in val_loader:
                features, targets = features.to(device), targets.to(device)
                outputs = model(features)
                loss = criterion(outputs, targets)
                val_loss += loss.item()
        
        val_loss /= len(val_loader)
        
        print(f"Epoch {epoch+1}/{epochs} - Train Loss: {train_loss:.4f}, Val Loss: {val_loss:.4f}")
        
        # Save best model
        if val_loss < best_val_loss:
            best_val_loss = val_loss
            export_weights(model, output_path)
            print(f"  → New best model saved!")
    
    print(f"\nTraining complete! Best validation loss: {best_val_loss:.4f}")
    print(f"Weights saved to: {output_path}")


def main():
    parser = argparse.ArgumentParser(
        description='Train NNUE network for Blunder chess engine'
    )
    parser.add_argument(
        '--input',
        type=str,
        default='training_data.bin',
        help='Input training data file (default: training_data.bin)'
    )
    parser.add_argument(
        '--output',
        type=str,
        default='nnue_weights.bin',
        help='Output weights file (default: nnue_weights.bin)'
    )
    parser.add_argument(
        '--epochs',
        type=int,
        default=10,
        help='Number of training epochs (default: 10)'
    )
    parser.add_argument(
        '--batch-size',
        type=int,
        default=256,
        help='Batch size (default: 256)'
    )
    parser.add_argument(
        '--learning-rate',
        type=float,
        default=0.001,
        help='Learning rate (default: 0.001)'
    )
    
    args = parser.parse_args()
    
    # Check input file exists
    if not Path(args.input).exists():
        print(f"Error: Input file '{args.input}' not found!")
        print("\nGenerate training data first:")
        print("  ./blunder --selfplay --selfplay-games 1000 --selfplay-output training_data.bin")
        return
    
    # Train
    train_nnue(
        data_path=args.input,
        output_path=args.output,
        epochs=args.epochs,
        batch_size=args.batch_size,
        learning_rate=args.learning_rate
    )


if __name__ == '__main__':
    main()
